version: '2'
services:

  proxy:
    image: unterstein/dcos-microservices-proxy:latest
    ports:
      - "8080:80"
    depends_on:
      - checkoutservice
      - articleservice
      - basketservice
      - webservice

  webservice:
    image: unterstein/dcos-microservices-web:latest

  checkoutservice:
    image: unterstein/dcos-microservices-checkout:latest
    depends_on:
      - articleservice
      - basketservice

  articleservice:
    image: unterstein/dcos-microservices-article:latest

  basketservice:
    image: unterstein/dcos-microservices-basket:latest
